# Keep all the files generated by this script in the same
# directory where this script is stored. This is the simplest way to make it work.
# It may be necessary to install widgetsnbextension and ipywidgets for
# correct working of the ydata_profiling package.
# See https://ipywidgets.readthedocs.io/en/stable/user_install.html
from pathlib import Path
from ydata_profiling import ProfileReport


def generate_profiling_report(df):
    # Use pathlib to create a path object that is OS-independent
    report_dir = Path(__file__).parent  # This gives the directory where the script is stored
    profile = ProfileReport(df, title="Profiling Report", explorative=True)
    # Save the report files in the same directory as the script
    profile.to_file(report_dir / "your_report.html")
    profile.to_file(report_dir / "your_report.json")
